# BOT CONFIGURATION OPTIONS

# Bot user agent
USER_AGENT = 'A bot that runs r/FutebolOnReddit. Created by u/Synergix for PortugalOnReddit, forked by u/tasey.'

# Subreddit where the bot will post
SUBREDDIT_TO_POST = 'FutebolOnReddit'

# Expressions to monitor for'
EXPRESSIONS_TO_MONITOR = [
'scolari',
'abel braga',
'felipão',
'renato gaúcho',
'fábio carille',
'eduardo barroca',
'rogério ceni',
'douglas friedrich',
'diogo silva',
'tiago volpi',
'marcelo lomba',
'fernando prass',
'gatito fernández',
'diego alves',
'éverson',
'felipe alves',
'danilo fernandes',
'paulo victor',
'diego cavalieri',
'sidão',
'marcelo boeck',
'marcos rocha',
'diogo barbosa',
'samuel xavier',
'nino paraíba',
'bruno pacheco',
'reinaldo',
'fábio santos',
'joão lucas',
'rafinha',
'mayke',
'victor ferraz',
'felipe jonatan',
'juninho capixaba',
'renan lodi',
'thiago carleto',
'victor luis',
'carlinhos',
'igor vinícius',
'danilo barcelos',
'danilo avelar',
'léo moura',
'bruno cortez',
'alan ruschel',
'bruno peres',
'alex silva',
'márcio azevedo',
'carlos cesar',
'rodinei',
'daniel guedes',
'rafael galhardo',
'orinho',
'igor julião',
'weverton',
'geromel',
'dedé',
'leandro castan',
'luiz otávio',
'rafael vaz',
'rodrigo caio',
'igor rabello',
'léo pereira',
'pedro henrique',
'lucas veríssimo',
'antônio carlos',
'edu dracena',
'joel carli',
'rodrigo moledo',
'bruno alves',
'matheus ferraz',
'emerson santos',
'marcelo oliveira',
'rhodolfo',
'léo duarte',
'paulo andré',
'roger carvalho',
'anderson martins',
'xandão',
'thiago heleno',
'nikão',
'everton ribeiro',
'hernanes',
'willian arão',
'pedrinho',
'bruno guimarães',
'hudson',
'jean mota',
'rodrigo lindoso',
'zé rafael',
'alex santana',
'thiago galhardo',
'bruno silva',
'matheus savio',
'yago pikachu',
'gustavo blanco',
'raphael veiga',
'márcio araújo',
'edenílson',
'thiago neves',
'jucilei',
'bruno césar',
'rodrigo dourado',
'renê júnior',
'júnior urso',
'léo sena',
'mateus vital',
'fabinho',
'felipe melo',
'caio henrique',
'didira',
'lucas mineiro',
'léo cittadini',
'fernando sobral',
'rodriguinho',
'vitor bueno',
'rithely',
'elicarlos',
'lucas lima',
'tomás andrade',
'wescley',
'juninho quixadá',
'matheus galdezani',
'matheus fernandes',
'liziero',
'thiago santos',
'josé welison',
'yago felipe',
'felipe bastos',
'hyoran',
'araruna',
'marcos júnior',
'lucas silva',
'tchê tchê',
'diego pituca',
'matheus rossetto',
'sarrafiore',
'marquinhos gabriel',
'bruno nazário',
'reinier',
'everton felipe',
'gustavo scarpa',
'gabigol',
'gabriel barbosa',
'bruno henrique',
'eduardo sasha',
'ricardo bueno',
'dudu',
'ricardo oliveira',
'geuvânio',
'arthur caíke',
'pedro rocha',
'leandro barcia',
'wellington paulista',
'deyverson',
'vitinho',
'rafael sóbis',
'rafael sobis',
'alexandre pato',
'fernandão',
'diego tardelli',
'arthur cabral',
'william pottker',
'júnior santos',
'carlos eduardo',
'felipe pires',
'keirrison',
'patrick fabiano',
'joão pedro',
'diego souza',
'wellington silva',
'romarinho',
'toró',
'helinho',
'vagner love',
'biro biro',
'victor andrade',
'ribamar',
'felipe vizeu',
'vinícius araújo',
'rodrigo pimpão',
'negueba',
'ricardo oliveira',
'rafael carioca',
'yago césar',
'nenê bonilha',
'ricardo ferretti',
'elsinho',
'jemerson',
'alex telles',
'caio secco',
'alan schons',
'tiquinho',
'luiz phellype',
'douglas grolli',
'militão',
'cafú',
'romarinho',
'maxwell',
'zé vitor',
'gil bahia',
'júnior caiçara',
'serginho',
'robinho',
'alan patrick',
'wellington nem',
'marcos cipriano',
'júnior dutra',
'bressan',
'everton luiz',
'andre shinyashiki',
'ilsinho',
'sergio santos',
'palmeiras',
'corinthians',
'spfc',
'flamengo',
'fluminense',
'botafogo',
'vasco',
'cruzeiro',
'atlético mineiro',
'atlético-mg',
'grêmio',
'sport recife',
'neymar',
'philippe coutinho',
'pelé',
'zico',
'garrincha',
'ronaldo fenômeno',
'ronaldo phenomenon',
'ronaldo nazário',
'gabriel jesus',
'filipe luís',
'marcelo vieira',
'dani alves',
'daniel alves',
'firmino',
'richarlison',
'david neres',
'lucas moura',
'felipe anderson',
'fernandinho',
'fabinho',
'david luiz',
'léo bonatini',
'guilherme arana',
'rafinha',
'douglas luiz',
'gabriel paulista',
'emerson palmieri',
'willian josé',
'casemiro',
'vinícius júnior',
'vinicius junior',
'vinícius jr',
'vinicius jr',
'rodrigo ely',
'bruno perone',
'gustavo assunção',
'gustavo assuncao',
'alex sandro',
'junior tavares',
'diego farias',
'lucas leiva',
'rafael tolói',
'rafael toloi',
'douglas costa',
'matheus pereira',
'lucas piazon',
'luan capanni',
'gabriel brazão',
'joão miranda',
'juan jesus',
'jandrei',
'vitor hugo',
'dalbert henrique',
'lyanco',
'ryder matos',
'wendell',
'ewerton',
'paulinho',
'matheus pereira',
'raffael',
'joelinton',
'lucas ribeiro',
'douglas santos',
'matheus cunha',
'andrei girotto',
'gabriel silva',
'thiago silva',
'fernando marçal',
'danilo barbosa',
'lucas evangelista',
'luiz araujo',
'sylvinho',
'boschilia',
'thiago mendes',
'luiz gustavo',
'thiago maia',
'mauro júnior',
'bruno andrade',
'david neres',
'ricardinho',
'eric botteghin',
'tiago pagnussat',
'andré ramalho',
'luan peres',
'fernando canesin',
'thallyson',
'renato neto',
'auro',
'felipe martins',
'lucas venuto',
'ricardo goulart',
'fabio lafundes',
'renato augusto',
'talisca',
'roger guedes',
'renatinho',
'elkeson',
'alex teixeira',
'marcão',
'fernandinho conceição',
'henrique dourado',
'rafael silva',
'léo baptistão',
'muriqui',
'victor bolt',
'keno',
'toró',
'léo jabá',
'lucão',
'leandro damião',
'leandro pereira',
'adailton',
'douglas vieira',
'lucas fernandes',
'joão schimidt',
]

# Subreddits to monitor for (+ to monitor multiple subreddits; - to exclude a subreddit)
SUBREDDITS_TO_MONITOR = 'all-FutebolOnReddit-BrasilOnReddit-brasil-a7arte-AJS_BR-Ajuda-AjudaBrasil-artebrasileira-batepapo-BeloHorizonte-bestofbrasil-Bolsonaro-Bovespa-br4r-brasil2-brasil420-brasil_drama-Brasilandia-Brasilball-BrasilBitcoin-brasildemocratico-BrasildoB-brasilivre-brasilpics-brazilianmusic-brdev-BRSExplica-brugal-carreiras-ciencias-CinemaBrasil-circojeca-concursospublicos-Corinthians-craftmybox-curitiba-desabafos-Dota2BRa-Dota2Brasil-Escalada-EscritoresBrasil-eu_nvr-filmes-filmeseseries-foradecasa-futebol-g1comments-Gambiarra-gororoba-investimentos-jogatina-jogos-leagueoflegendsbrazil-Libertarianismo-linuxbrasil-Livros-maconha-Maromba-masqueporra-medoiosoio-merdasbrasildiz-Monarquia-motoca-MUSICA-musicanova-naoesensacionalista-NerdPowerBR-oBitcoin-palmeiras-Parana-PokemonGOBrasil-Portuguese-Psicanalise-Recife-riodejaneiro-riograndedosul-saopaulo-Semeando-southamerica-territoriolivre-tiodopave-veganismobrasil-youtubebrasil-ZeroQuatroMidia'

# Number of submissions to check in each run
SEARCH_LIMIT = 8000

# Blacklist, disconsider posts that contains all of the words of a index
BLACKLIST = []

# Wait time between runs (in minutes)
WAIT_TIME = 15

# Post mode (choose 'direct' or 'comment')
# 'direct' will make the bot post the direct link of the source submission
# 'comment' will make the bot post the link to the comment section of the source submission
POST_MODE = 'comment'

# Required score to cross-post a submission found by search when setting up your subreddit
REQUIRED_SCORE = 500
